### ISSUE TITLE
Error when building

### ISSUE THREAD

**Issue by dalareo** [OpenSaasAU/edx-docker-ansible#1]
At task "TASK [edxapp : checkout edx-platform repo into /edx/app/edxapp/edx-platform]" I get:

````
fatal: [lms]: FAILED! => {"changed": false, "cmd": "/usr/bin/git clone --origin origin --branch release https://github.com/edx/edx-platform.git /edx/app/edxapp/edx-platform", "failed": true, "msg": "Cloning into '/edx/app/edxapp/edx-platform'...\n/edx/app/edxapp/edx-platform/.git: Permission denied", "rc": 1, "stderr": "Cloning into '/edx/app/edxapp/edx-platform'...\n/edx/app/edxapp/edx-platform/.git: Permission denied\n", "stdout": "", "stdout_lines": []}
````

It is not using "git_2_0_1" but "git", could it be the reason?
https://raw.githubusercontent.com/OpenSaasAU/edx-docker-ansible/master/ansible/roles/edxapp/tasks/deploy.yml

**Comment by borisno2** [comment]
Hi @dalareo,
For the edxapp clone Docker needs to be able to write to the local file system as the edxapp user. Easiest way to fix is `chmod 777 /path/to/edxapp/edx-platform` OR `chown 1002:1002 /path/to/edxapp/edx-platform`
Hope this helps! Let me know how you go.

**Comment by dalareo** [comment]
It solves the issue. Thanks! Keep on building!

**Comment by dalareo** [comment]
Same issue here?

fatal: [analytics]: FAILED! => {"changed": true, "cmd": "DB_MIGRATION_USER='root' DB_MIGRATION_PASS='password' /edx/app/analytics/venvs/analytics/bin/python ./manage.py migrate --noinput", "delta": "0:00:00.204642", "end": "2016-12-28 03:37:42.064722", "failed": true, "rc": 1, "start": "2016-12-28 03:37:41.860080", "stderr": "Traceback (most recent call last):\n  File \"./manage.py\", line 10, in <module>\n    execute_from_command_line(sys.argv)\n  File \"/edx/app/analytics/venvs/analytics/local/lib/python2.7/site-packages/django/core/management/__init__.py\", line 353, in execute_from_command_line\n    utility.execute()\n  File \"/edx/app/analytics/venvs/analytics/local/lib/python2.7/site-packages/django/core/management/__init__.py\", line 302, in execute\n    settings.INSTALLED_APPS\n  File \"/edx/app/analytics/venvs/analytics/local/lib/python2.7/site-packages/django/conf/__init__.py\", line 55, in __getattr__\n    self._setup(name)\n  File \"/edx/app/analytics/venvs/analytics/local/lib/python2.7/site-packages/django/conf/__init__.py\", line 43, in _setup\n    self._wrapped = Settings(settings_module)\n  File \"/edx/app/analytics/venvs/analytics/local/lib/python2.7/site-packages/django/conf/__init__.py\", line 99, in __init__\n    mod = importlib.import_module(self.SETTINGS_MODULE)\n  File \"/usr/lib/python2.7/importlib/__init__.py\", line 37, in import_module\n    __import__(name)\n  File \"/edx/app/analytics/analytics/analyticsdataserver/settings/production.py\", line 31, in <module>\n    with open(CONFIG_FILE) as f:\nIOError: [Errno 2] No such file or directory: '/edx/etc/analytics.yml'", "stdout": "", "stdout_lines": [], "warnings": []}

**Comment by borisno2** [comment]
Hmm looks to be a different issue. Looks like it can't find the config file /edx/etc/analytics.yml this file should have been created during the edx_service role dependency. This file is stored in the docker image itself not on local disk. If you scroll back up in the logs can you see something like `TASK [edx-service: Write out app config file]`? has it changed or skipped? Can you `docker cp ansible_analytics_1:/edx/etc/analytics.yml .` if not can you run `docker cp ansible_analytics_1:/edx/etc/analytics_api.yml .`?
Let me know how you go..

**Comment by dalareo** [comment]
Do you want me to open a new issue for this?

**Comment by borisno2** [comment]
Yeah good idea.. Thanks..

**Comment by dalareo** [comment]
Regarding folder permissions issue, is it possible to avoid cloning repositories and do it manually before building?
