### ISSUE TITLE
linux spec user: unable to find user root: no matching entries in passwd file

### ISSUE THREAD

**Issue by SalahAdDin** [OpenSaasAU/edx-docker-ansible#10]
As you can see [here](https://github.com/ansible/ansible-container/issues/400), exist a problem if we haven't all docker images needed in our local environtment.

I test it, is truth, so, i think that for now is necessary put instructions in the build script for pull the images before build the container.

**Comment by borisno2** [comment]
Issue has now been solved in ansible-container need to use source or wait until 0.9.2
