### ISSUE TITLE
Customization options in yaml files

### ISSUE THREAD

**Issue by SalahAdDin** [OpenSaasAU/edx-docker-ansible#12]
I'm trying to use this for build in production the entire platform.

I have other issue but in this case i want ask about internazionalization features.

Reading the documentation we can find that we have to modify some settings in the playbooks:

> Configure EDXAPP_LANGUAGE_CODE in your configuration files: https://github.com/edx/configuration/blob/master/playbooks/roles/edxapp/defaults/main.yml#L282

Is this:
```
EDXAPP_LANG: 'en_US.UTF-8'
EDXAPP_LANGUAGE_CODE : 'en'
EDXAPP_LANGUAGE_COOKIE: 'openedx-language-preference'
EDXAPP_TIME_ZONE: 'America/New_York'
```

Some clients need change this options, and i think will be good add this options in the variables files.

What do you think guys?

**Comment by borisno2** [comment]
@SalahAdDin you can add whatever you would like to your custom `edxapp_vars.yaml` file to customise edx as much as you need to. I have just put in what is required to be overridden (ie passwords etc) or what is shared between containers. But you can customise your variable file by simply adding whatever edxapp variables you would like. any variables you put in your file will then be passed into the edx build.
