### ISSUE TITLE
Complete or more clearly application tutorial.

### ISSUE THREAD

**Issue by SalahAdDin** [OpenSaasAU/edx-docker-ansible#7]
Hi, i was searching a `docker` infrastructure tutorial for install `OpenEDX` instead use `Vagrant`, so thank you.

But i tried to use `ansible-container` for built this repo and i doesn't works.

Doesn't make anything, doesn't show me problems, or build the images or make other, nothing.

Maybe is because i don't know how works this infrastructure, so, i want ask you a more clearle or completly tutorial for apply it.

**Comment by borisno2** [comment]
Hi @SalahAdDin 
It's hard to know what you mean without knowing what you are doing exactly.
Have you followed the instructions to install ansible-container?
Are you then cloning the repo locally and running `./ansible-build.sh` as per the README?
What OS are you using? 
When you run this command it should build the required containers so that then `./ansible-run.sh` runs the full docker environment.
Thanks, and happy to help, just need to know where I can help and where you are getting stuck.

**Comment by SalahAdDin** [comment]
i think a more complete steps:

My first time i didn't know that  i have to download all repositories in the project directory for work.

So, when i execute ansible i haven't problems, actually i haven't nothing:
Running:
```bash
./ansible-build.sh                                                                    ✓  850  13:21:08 
Building Docker Engine context...	
Starting Docker build of Ansible Container Conductor image (please be patient)...	
Parsing conductor CLI args.
Docker™ daemon integration engine loaded. Build starting.	project=None
All images successfully built.
Conductor terminated. Cleaning up.	command_rc=0 conductor_id=bbb5a47adbfd930e90c2279959461271655ac452be66882101e22433e08f9113 save_container=False
```
Building:
```
./ansible-run.sh                                                                      ✓  851  13:21:41 
Parsing conductor CLI args.
Engine integration loaded. Preparing run.	engine=Docker™ daemon
 [WARNING]: provided hosts list is empty, only localhost is available

PLAY [localhost] ***************************************************************

TASK [docker_service] **********************************************************
ok: [localhost]

PLAY RECAP *********************************************************************
localhost                  : ok=1    changed=0    unreachable=0    failed=0

All services running.	playbook_rc=0
Conductor terminated. Cleaning up.	command_rc=0 conductor_id=5b90b8002cc2374e2b5f962925220e32b67625250e5e0f0dfbb28a18033f581d save_container=False
```

I have this in my `virtualenv`:
```bash
pip list                                                                              ✓  852  13:23:05 
DEPRECATION: The default format will switch to columns in the future. You can use --format=(legacy|columns) (or define a format=(legacy|columns) in your pip.conf under the [list] section) to disable this warning.
ansible-container (0.9.1rc0, /home/salahaddin/Proyectos/Works/edx-ansible/edx-docker-ansible/ansible-container)
appdirs (1.4.3)
colorama (0.3.9)
docker (2.3.0)
docker-py (1.8.0)
docker-pycreds (0.2.1)
Jinja2 (2.9.6)
MarkupSafe (1.0)
packaging (16.8)
pip (9.0.1)
pyparsing (2.2.0)
PyYAML (3.12)
requests (2.14.2)
ruamel.yaml (0.14.12)
setuptools (35.0.2)
six (1.10.0)
structlog (17.2.0)
websocket-client (0.40.0)
wheel (0.29.0)
```

My system is:
`Antergos Linux x64`
`Docker version 17.05.0-ce, build 89658bed64`

**Comment by SalahAdDin** [comment]
@borisno2 :+1:

**Comment by borisno2** [comment]
@SalahAdDin does that mean you have sorted it out?
What was the issue?

**Comment by SalahAdDin** [comment]
Is not clearly all steps for begginer users.

Before to run ansible which things are required?

**Comment by borisno2** [comment]
@SalahAdDin sorry I just realised ansible-container has had some major changes in the last couple of releases, I am looking into making the required changes to make it work with the latest version (0.9.1) currently is only works with versions 0.3 and 0.2.

This is why it is not working for you...

**Comment by SalahAdDin** [comment]
Versions of what? I don't understand you. I'm relatively new with `ansible`.

**Comment by borisno2** [comment]
The ansible-container version... if you `pip install ansible-conatainer==0.2` and then run `./ansible-build.sh` is should work. If not, hopefully I will have a version up soon that works with the latest version of ansible-conatiner.

**Comment by SalahAdDin** [comment]
Oh man please, we need it, thank you very much. 
@borisno2 :+1:

**Comment by SalahAdDin** [comment]
@borisno2 If i don't wrong, we have to download all release version for all `edx` packages and put them in the project directory, isn't it?

**Comment by borisno2** [comment]
@SalahAdDin no, running `./ansible-build.sh` should be all you need to do once all the issues are sorted out with 0.9
